---
- name: Deploy Python Service
  hosts: localhost
  become: true

  tasks:
    - name: Clone the repository
      git:
        repo: 'git@github.com:vandavision/systemctl.git'
        dest: /tmp/systemctl
        version: master

    - name: Copy Python script to /usr/local/bin
      copy:
        src: /tmp/systemctl/script.py
        dest: /usr/local/bin/script.py
        mode: 0755

    - name: Copy service file
      copy:
        src: /tmp/systemctl/my_python_service.service
        dest: /etc/systemd/system/my_python_service.service

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Enable and start the service
      systemd:
        name: my_python_service
        enabled: yes
        state: started
