---
- name: Deploy Python Script as a Service
  hosts: localhost
  become: yes
  tasks:
    - name: Clone repository from Git
      git:
        repo: 'https://github.com/vandavision/systemctl.git'
        dest: /tmp/my_service_repo
        version: main
      delegate_to: localhost

    - name: Copy Python script to destination
      copy:
        src: /tmp/my_service_repo/script.py
        dest: /usr/local/bin/script.py
        mode: '0755'

    - name: Copy systemd service file to systemd directory
      copy:
        src: /tmp/my_service_repo/my_python_service.service
        dest: /etc/systemd/system/my_python_service.service
        mode: '0644'

    - name: Reload systemd daemon to recognize the new service
      command: systemctl daemon-reload

    - name: Enable the service to start on boot
      systemd:
        name: my_python_service
        enabled: yes

    - name: Start the service
      systemd:
        name: my_python_service
        state: started

    - name: Check service status
      command: systemctl status my_python_service
      register: service_status

    - name: Display service status
      debug:
        var: service_status.stdout
